hl.on("hyprland.start", function()
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("WGPU_BACKEND=gl ashell --config-path $HOME/.config/hypr/ashell.toml")
  hl.exec_cmd("hyprlauncher -d")
  hl.exec_cmd("swaync")
  hl.exec_cmd("swayosd-server")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
  hl.exec_cmd("/usr/lib/xdg-desktop-portal-gtk")
  hl.exec_cmd("hypridle")
end)
